name: Log data to google sheet

on:
#  push:
#    branches: master
  workflow_dispatch:

  schedule:
    - cron: "30 6 * * *" # 12:30 AM CENTRAL TIME

jobs:
  log-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: npm install
      - name: Fetch data from wakatime & log to google sheet
        run: npm run do-the-thing
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GOOGLE_SA_B64: ${{ secrets.GOOGLE_SA_B64 }}
          GOOGLE_SHEETS_ID: ${{ secrets.GOOGLE_SHEETS_ID }}
